Get-ComputerInfo | Select-Object -Property @{Name= 'BiosBIOSVersion'; Expression= {[string]$_.BiosBIOSVersion -join ','}},
BiosBuildNumber,
BiosCaption,
@{Name= 'BiosCharacteristics'; Expression= {[string]$_.BiosCharacteristics -join ','}},
BiosCodeSet,
BiosCurrentLanguage,
BiosDescription,
BiosEmbeddedControllerMajorVersion,
BiosEmbeddedControllerMinorVersion,
BiosFirmwareType,
BiosIdentificationCode,
BiosInstallableLanguages,
BiosInstallDate,
BiosLanguageEdition,
@{Name= 'BiosListOfLanguages'; Expression= {[string]$_.BiosListOfLanguages -join ','}},
BiosManufacturer,
BiosName,
BiosOtherTargetOS,
BiosPrimaryBIOS,
BiosReleaseDate,
BiosSeralNumber,
BiosSMBIOSBIOSVersion,
BiosSMBIOSMajorVersion,
BiosSMBIOSMinorVersion,
BiosSMBIOSPresent,
BiosSoftwareElementState,
BiosStatus,
BiosSystemBiosMajorVersion,
BiosSystemBiosMinorVersion,
BiosTargetOperatingSystem,
BiosVersion,
CsAdminPasswordStatus,
CsAutomaticManagedPagefile,
CsAutomaticResetBootOption,
CsAutomaticResetCapability,
CsBootOptionOnLimit,
CsBootOptionOnWatchDog,
CsBootROMSupported,
@{Name= 'CsBootStatus'; Expression= {[string]$_.CsBootStatus -join ','}},
CsBootupState,
CsCaption,
CsChassisBootupState,
CsChassisSKUNumber,
CsCurrentTimeZone,
CsDaylightInEffect,
CsDescription,
CsDNSHostName,
CsDomain,
CsDomainRole,
CsEnableDaylightSavingsTime,
CsFrontPanelResetStatus,
CsHypervisorPresent,
CsInfraredSupported,
CsInitialLoadInfo,
CsInstallDate,
CsKeyboardPasswordStatus,
CsLastLoadInfo,
CsManufacturer,
CsModel,
CsName,
@{Name= 'CsNetworkAdapters.Description'; Expression= {[string]$_.CsNetworkAdapters.Description -join ','}},
@{Name= 'CsNetworkAdapters.IPAddresses'; Expression= {[string]$_.CsNetworkAdapters.IPAddresses -join ','}},
CsNetworkServerModeEnabled,
CsNumberOfLogicalProcessors,
CsNumberOfProcessors,
@{Name= 'CsOEMStringArray'; Expression= {[string]$_.CsOEMStringArray -join ','}},
CsPartOfDomain,
CsPauseAfterReset,
CsPCSystemType,
CsPCSystemTypeEx,
CsPhyicallyInstalledMemory,
CsPowerManagementCapabilities,
CsPowerManagementSupported,
CsPowerOnPasswordStatus,
CsPowerState,
CsPowerSupplyState,
CsPrimaryOwnerContact,
CsPrimaryOwnerName,
CsProcessors.Name,
CsResetCapability,
CsResetCount,
CsResetLimit,
@{Name= 'CsRoles'; Expression= {[string]$_.CsRoles -join ','}},
CsStatus,
CsSupportContactDescription,
CsSystemFamily,
CsSystemSKUNumber,
CsSystemType,
CsThermalState,
CsTotalPhysicalMemory,
CsUserName,
CsWakeUpType,
CsWorkgroup,
@{Name= 'DeviceGuardAvailableSecurityProperties'; Expression= {[string]$_.DeviceGuardAvailableSecurityProperties -join ','}},
DeviceGuardCodeIntegrityPolicyEnforcementStatus,
@{Name= 'DeviceGuardRequiredSecurityProperties'; Expression= {[string]$_.DeviceGuardRequiredSecurityProperties -join ','}},
@{Name= 'DeviceGuardSecurityServicesConfigured'; Expression= {[string]$_.DeviceGuardSecurityServicesConfigured -join ','}},
@{Name= 'DeviceGuardSecurityServicesRunning'; Expression= {[string]$_.DeviceGuardSecurityServicesRunning -join ','}},
DeviceGuardSmartStatus,
DeviceGuardUserModeCodeIntegrityPolicyEnforcementStatus,
HyperVisorPresent,
HyperVRequirementDataExecutionPreventionAvailable,
HyperVRequirementSecondLevelAddressTranslation,
HyperVRequirementVirtualizationFirmwareEnabled,
HyperVRequirementVMMonitorModeExtensions,
KeyboardLayout,
LogonServer,
OsArchitecture,
OsBootDevice,
OsBuildNumber,
OsBuildType,
OsCodeSet,
OsCountryCode,
OsCSDVersion,
OsCurrentTimeZone,
OsDataExecutionPrevention32BitApplications,
OsDataExecutionPreventionAvailable,
OsDataExecutionPreventionDrivers,
OsDataExecutionPreventionSupportPolicy,
OsDebug,
OsDistributed,
OsEncryptionLevel,
OsForegroundApplicationBoost,
OsFreePhysicalMemory,
OsFreeSpaceInPagingFiles,
OsFreeVirtualMemory,
OsHardwareAbstractionLayer,
@{Name= 'OsHotFixes.HotFixID'; Expression= {[string]$_.OsHotFixes.HotFixID -join ','}},
OsInstallDate,
OsInUseVirtualMemory,
OsLanguage,
OsLastBootUpTime,
OsLocalDateTime,
OsLocale,
OsLocaleID,
OsManufacturer,
OsMaxNumberOfProcesses,
OsMaxProcessMemorySize,
@{Name= 'OsMuiLanguages'; Expression= {[string]$_.OsMuiLanguages -join ','}},
OsName,
OsNumberOfLicensedUsers,
OsNumberOfProcesses,
OsNumberOfUsers,
OsOperatingSystemSKU,
OsOrganization,
OsOtherTypeDescription,
OsPAEEnabled,
@{Name= 'OsPagingFiles'; Expression= {[string]$_.OsPagingFiles -join ','}},
OsPortableOperatingSystem,
OsPrimary,
@{Name= 'OsProductSuites'; Expression= {[string]$_.OsProductSuites -join ','}},
OsProductType,
OsRegisteredUser,
OsSerialNumber,
OsServerLevel,
OsServicePackMajorVersion,
OsServicePackMinorVersion,
OsSizeStoredInPagingFiles,
OsStatus,
@{Name= 'OsSuites'; Expression= {[string]$_.OsSuites -join ','}},
OsSystemDevice,
OsSystemDirectory,
OsSystemDrive,
OsTotalSwapSpaceSize,
OsTotalVirtualMemorySize,
OsTotalVisibleMemorySize,
OsType,
OsUptime,
OsVersion,
OsWindowsDirectory,
PowerPlatformRole,
TimeZone,
WindowsBuildLabEx,
WindowsCurrentVersion,
WindowsEditionId,
WindowsInstallationType,
WindowsInstallDateFromRegistry,
WindowsProductId,
WindowsProductName,
WindowsRegisteredOrganization,
WindowsRegisteredOwner,
WindowsSystemRoot,
WindowsVersion | Export-Csv -NoTypeInformation -Path "~\Documents\ComputerInfo.csv"
