Get-ScheduledTask | Select-Object -Property TaskName,
Author,
Date,
Description,
State,
@{Name= 'Actions.execute'; Expression= {[string]$_.Actions.execute}},
@{Name= 'Actions.Arguments'; Expression= {[string]$_.Actions.Arguments}},
@{Name= 'LastRunTime'; Expression= {(($_ | Get-ScheduledTaskInfo).LastRunTime)}},
@{Name= 'LastTaskResult'; Expression= {(($_ | Get-ScheduledTaskInfo).LastTaskResult)}},
@{Name= 'NextRunTime'; Expression= {(($_ | Get-ScheduledTaskInfo).NextRunTime)}},
Version,
TaskPath,
Documentation,
@{Name= 'Principal.UserID'; Expression= {[string]$_.Principal.UserID}},
PSComputerName,
SecurityDescriptor,
@{Name= 'Settings.AllowDemandStart'; Expression= {[string]$_.Settings.AllowDemandStart}},
@{Name= 'Settings.AllowHardTerminate'; Expression= {[string]$_.Settings.AllowHardTerminate}},
@{Name= 'Settings.Compatibility'; Expression= {[string]$_.Settings.Compatibility}},
@{Name= 'Settings.DeleteExpiredTaskAfter'; Expression= {[string]$_.Settings.DeleteExpiredTaskAfter}},
@{Name= 'Settings.DisallowStartIfOnBatteries'; Expression= {[string]$_.Settings.DisallowStartIfOnBatteries}},
@{Name= 'Settings.ExecutionTimeLimit'; Expression= {[string]$_.Settings.ExecutionTimeLimit}},
@{Name= 'Settings.Hidden'; Expression= {[string]$_.Settings.Hidden}},
@{Name= 'Settings.MultipleInstances'; Expression= {[string]$_.Settings.MultipleInstances}},
@{Name= 'Settings.Priority'; Expression= {[string]$_.Settings.Priority}},
@{Name= 'Settings.RestartCount'; Expression= {[string]$_.Settings.RestartCount}},
@{Name= 'Settings.RestartInterval'; Expression= {[string]$_.Settings.RestartInterval}},
@{Name= 'Settings.RunOnlyIfIdle'; Expression= {[string]$_.Settings.RunOnlyIfIdle}},
@{Name= 'Settings.RunOnlyIfNetworkAvailable'; Expression= {[string]$_.Settings.RunOnlyIfNetworkAvailable}},
@{Name= 'Settings.StartWhenAvailable'; Expression= {[string]$_.Settings.StartWhenAvailable}},
@{Name= 'Settings.StopIfGoingOnBatteries'; Expression= {[string]$_.Settings.StopIfGoingOnBatteries}},
@{Name= 'Settings.WakeToRun'; Expression= {[string]$_.Settings.WakeToRun}},
Source,
URI
