Get-CimInstance -ClassName 'Win32_BIOS' | Select-Object -Property Name,
Status,
Caption,
Description,
InstallDate,
ReleaseDate,
BuildNumber,
CodeSet,
IdentificationCode,
LanguageEdition,
Manufacturer,
OtherTargetOS,
SerialNumber,
SoftwareElementID,
SoftwareElementState,
TargetOperatingSystem,
Version,
PrimaryBIOS,
@{Name= 'BiosCharacteristics'; Expression={[string]$_.BiosCharacteristics -join ','}},
@{Name= 'BIOSVersion'; Expression={[string]$_.BIOSVersion -join ','}},
CurrentLanguage,
EmbeddedControllerMajorVersion,
EmbeddedControllerMinorVersion,
InstallableLanguages,
@{Name= 'ListOfLanguages'; Expression={[string]$_.ListOfLanguages -join ','}},
SMBIOSBIOSVersion,
SMBIOSMajorVersion,
SMBIOSMinorVersion,
SMBIOSPresent,
SystemBiosMajorVersion,
SystemBiosMinorVersion
