Get-CimInstance -ClassName 'Win32_PNPEntity' | Select-Object -Property Name,
Status,
StatusInfo,
Manufacturer,
PNPClass,
Present,
Service,
Caption,
ClassGuid,
CompatibleID,
ConfigManagerErrorCode,
ConfigManagerUserConfig,
Description,
DeviceID,
ErrorCleared,
ErrorDescription,
@{Name= 'HardwareID'; Expression= {[string]$_.HardwareID}},
InstallDate,
LastErrorCode,
PNPDeviceID,
Availability,
PowerManagementCapabilities,
PowerManagementSupported
