Get-DnsClientGlobalSetting | Select-Object -Property Caption,
Description,
ElementName,
InstanceID,
AddressOrigin,
ProtocolIFType,
AppendParentSuffixes,
AppendPrimarySuffixes,
@{Name= 'DNSSuffixesToAppend'; Expression= {[string]$_.DNSSuffixesToAppend -join "'"}},
DevolutionLevel,
@{Name= 'SuffixSearchList'; Expression= {[string]$_.SuffixSearchList -join ','}},
UseDevolution,
UseSuffixSearchList
