Get-LocalUser | Select-Object -Property Name,
FullName,
Description,
Enabled,
AccountExpires,
PasswordChangeableDate,
PasswordExpires,
UserMayChangePassword,
PasswordRequired,
PasswordLastSet,
LastLogon,
SID,
PrincipalSource,
ObjectClass
