Get-NetIPConfiguration | Select-Object -Property InterfaceAlias,
@{Name= 'AllIPAddresses'; Expression= {[string]$_.AllIPAddresses.IPAddress -join ','}},
CompartmentId,
ComputerName,
Detailed,
@{Name= 'DNSServer'; Expression= {[string]$_.DNSServer.ServerAddresses -join ','}},
InterfaceDescription,
InterfaceIndex,
@{Name= 'IPv4Address'; Expression= {[string]$_.IPv4Address}},
@{Name= 'IPv4DefaultGateway'; Expression= {[string]$_.IPv4DefaultGateway.NextHop}},
@{Name= 'IPv6Address'; Expression= {[string]$_.IPv6Address -join ','}},
@{Name= 'IPv6DefaultGateway'; Expression= {[string]$_.IPv6DefaultGateway.NextHop -join ','}},
@{Name= 'IPv6LinkLocalAddress'; Expression= {[string]$_.IPv6LinkLocalAddress -join ','}},
@{Name= 'IPv6TemporaryAddress'; Expression= {[string]$_.IPv6TemporaryAddress}},
@{Name= 'NetAdapter.Name'; Expression= {[string]$_.NetAdapter.Name}},
@{Name= 'NetIPv4Interface'; Expression= {[string]$_.NetIPv4Interface.InterfaceAlias}},
@{Name= 'NetIPv6Interface'; Expression= {[string]$_.NetIPv6Interface.InterfaceAlias}},
@{Name= 'NetProfile'; Expression= {[string]$_.NetProfile.NetworkCategory}}
